### ISSUE TITLE
Training code on Calvin

### ISSUE THREAD

**Issue by yueyang130** [kvablack/susie#1]
Hi, Thanks for your excellent work!

I'm wondering whether you can release the Training code on Calvin?

**Comment by kvablack** [comment]
If you mean the high-level subgoal generation, you can just use this repo (see the "calvin" entry in `configs/base.py`). For generating the TFRecord dataset, and also training the low-level policy, see https://github.com/rail-berkeley/bridge_data_v2/tree/main/experiments/susie/calvin.

**Comment by COST-97** [comment]
Hello:
    For high-level subgoal policy training, do you use the language-picture pairs from all CALVIN data (i.e., the four environments ABCD) or the data from the three environments ABC?
   Thanks!

**Comment by weitliu** [comment]
@kvablack Hello. May I ask what the exact tr_record data to train Calvin? In the link, there are goal_conditioned.py  
language_conditioned.py to generate the tf record. I tried both in https://github.com/kvablack/susie/blob/main/configs/base.py#L112, but I still got a dataloader error:

  File "susie/susie/data/datasets.py", line 146, in get_data_loader
    train_datasets.append(make_dataset(data_name, train=True, **data_kwargs))
  File "/.conda/envs/calvin/lib/python3.8/bdb.py", line 88, in trace_dispatch
    return self.dispatch_line(frame)
  File "/.conda/envs/calvin/lib/python3.8/bdb.py", line 113, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit

Thank you!
