### ISSUE TITLE
Missing config file for Calvin-sim checkpoint

### ISSUE THREAD

**Issue by Ping-C** [kvablack/susie#4]
Hello Kevin,

I tried evaluation your model using `./eval_susie.sh.` under the calvin-sim (https://github.com/pranavatreya/calvin-sim) repo. I found that I could not use the checkpoint that you have shared here https://huggingface.co/patreya/susie-calvin-checkpoints/tree/main because it does not contain configs for the models. Would you mind either pushing the configs onto huggingface or share where I could find the corresponding config, especially for the gc_policy?

Thanks,

**Comment by Ping-C** [comment]
Hello, I didn't realize these are orbax checkpoints. I thought these are huggingface checkpoints. I am now able to load the checkpoints with no problem

**Comment by zlm200** [comment]
Hello, I'm having the same problem, please how did you load successfully
