### ISSUE TITLE
pretrained model weights

### ISSUE THREAD

**Issue by xbxsxp** [kvablack/susie#7]
hello，may I ask where stable-diffusion-v1-5:flax: Flax can obtain these model weight files？

**Comment by kvablack** [comment]
That just refers to the "flax" branch of the official Stable Diffusion v1-5 repo: https://huggingface.co/runwayml/stable-diffusion-v1-5/tree/flax

The code should handle the string "stable-diffusion-v1-5:flax" automatically if you pass it in!

**Comment by huoxingdawang** [comment]
Hello, the url [https://huggingface.co/runwayml/stable-diffusion-v1-5/tree/flax](https://huggingface.co/runwayml/stable-diffusion-v1-5/tree/flax) is 404 now, and the code can not download the weight too, it reported.

```
 File "/root/miniconda3/envs/susie/lib/python3.10/site-packages/huggingface_hub/utils/_http.py", line 406, in hf_raise_f                         or_status
    response.raise_for_status()
  File "/root/miniconda3/envs/susie/lib/python3.10/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/stable-diffusion-v1-5/stable-d                         iffusion-v1-5/resolve/flax/vae/config.json
```
